####################
# Role
####################
###
GET http://localhost:5000/role

###
GET http://localhost:5000/role/1

###
POST  http://localhost:5000/role
Content-Type: application/json

{
    "name": "Pelanggan"
}

###
PATCH  http://localhost:5000/role/3
Content-Type: application/json

{
    "name": "Pegawai"
}

###
DELETE  http://localhost:5000/role/3
Content-Type: application/json

{
    "name": "Pelanggan"
}

####################
# User
####################
###
GET http://localhost:5000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VyTmFtZSI6IkFkbWluIDIiLCJ1c2VyRW1haWwiOiJhZG1pbjJAZ21haWwuY29tIiwiaWF0IjoxNzExNTUzOTY2LCJleHAiOjE3MTE1NTM5ODZ9.YBmJ_lWdsut499baXM0OFyy1bsjhtVB9O4hqK0QzGD8

###
GET http://localhost:5000/user/1

###
POST  http://localhost:5000/user
Content-Type: application/json

{
    "name": "Pelanggan 3",
    "email": "pelanggan3@gmail.com",
    "password": "12345678",
    "role_id": 3
}

###
POST  http://localhost:5000/user/register
Content-Type: application/json

{
    "name": "Admin 2",
    "email": "admin2@gmail.com",
    "password": "12345678",
    "rePassword": "12345678",
    "role_id": 1
}

###
POST  http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "admin2@gmail.com",
    "password": "12345678"
}

###
GET  http://localhost:5000/user/token

###
PATCH  http://localhost:5000/user/3
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@gmail.com",
    "password": "12345678",
    "role_id": 1
}

###
DELETE  http://localhost:5000/user/1
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@gmail.com",
    "password": "12345678",
    "role_id": 1
}