####################
# Role
####################
###
GET http://localhost:5000/role

###
GET http://localhost:5000/role/1

###
POST  http://localhost:5000/role
Content-Type: application/json

{
    "name": "Admin"
}

###
PATCH  http://localhost:5000/role/3
Content-Type: application/json

{
    "name": "Pegawai"
}

###
DELETE  http://localhost:5000/role/3
Content-Type: application/json

{
    "name": "Pelanggan"
}

####################
# User
####################
###
GET http://localhost:5000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJOYW1lIjoiQWRtaW4iLCJ1c2VyRW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE3MTE2MDU4MzQsImV4cCI6MTcxMTYwNTg0OX0.O2QjPkPW0ohZ9W0IVPQEjQWujULjgXKuX89b0C1jtJo

###
GET http://localhost:5000/user/1

###
POST  http://localhost:5000/user
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@gmail.com",
    "password": "12345678",
    "role_id": 1
}

###
POST  http://localhost:5000/user/register
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@gmail.com",
    "password": "12345678",
    "rePassword": "12345678",
    "role_id": 1
}

###
POST  http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "12345678"
}

###
GET  http://localhost:5000/user/token

###
PATCH  http://localhost:5000/user/3
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@gmail.com",
    "password": "12345678",
    "role_id": 1
}

###
DELETE  http://localhost:5000/user/1
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@gmail.com",
    "password": "12345678",
    "role_id": 1
}